Repository Brisanet/ion, pull requests merged in 2022-10, with the labels that each got.

#168 :sparkles: add info badge in chip #147
  README.md
  projects/ion/src/lib/chip/chip.component.html
  projects/ion/src/lib/chip/chip.component.spec.ts
  projects/ion/src/lib/chip/chip.component.ts
  projects/ion/src/public-api.ts
  stories/Chip.stories.ts
Labels: hacktoberfest

#119 ✨ Pagination component
  projects/ion/src/lib/button/button.component.scss
  projects/ion/src/lib/ion.module.ts
  projects/ion/src/lib/pagination/pagination.component.html
  projects/ion/src/lib/pagination/pagination.component.scss
  projects/ion/src/lib/pagination/pagination.component.spec.ts
  projects/ion/src/lib/pagination/pagination.component.ts
  stories/Pagination.stories.ts
Labels: hacktoberfest, important

#178 fix: label and id of radio and add new icons #175
  projects/ion/src/lib/icon/svgs/icons.ts
  projects/ion/src/lib/icon/svgs/iconsText/doc-add.ts
  projects/ion/src/lib/icon/svgs/iconsText/doc.ts
  projects/ion/src/lib/icon/svgs/iconsText/index.ts
  projects/ion/src/lib/icon/svgs/iconsText/service-internet.ts
  projects/ion/src/lib/icon/svgs/iconsText/service-phone.ts
  projects/ion/src/lib/icon/svgs/iconsText/service-tv.ts
  projects/ion/src/lib/radio/radio.component.html
  projects/ion/src/lib/radio/radio.component.scss
Labels: hacktoberfest

#210 feat: added new files icon #173
  projects/ion/src/lib/icon/svgs/icons.ts
  projects/ion/src/lib/icon/svgs/iconsText/doc-check.ts
  projects/ion/src/lib/icon/svgs/iconsText/doc-close.ts
  projects/ion/src/lib/icon/svgs/iconsText/doc-warning.ts
  projects/ion/src/lib/icon/svgs/iconsText/index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#208 Change color svg
  projects/ion/src/lib/simple-menu/simple-menu.component.html
Labels: hacktoberfest, hacktoberfest-accepted

#206 Change padding
  projects/ion/src/lib/card/card.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#203 Change hover color
  projects/ion/src/lib/table/table.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#204 Change border color
  projects/ion/src/lib/chip/chip.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#170 fix: autoclose in dropdown when select an option
  projects/ion/src/lib/chip/chip.component.spec.ts
  projects/ion/src/lib/chip/chip.component.ts
Labels: hacktoberfest

#217 Update badge.component.scss
  projects/ion/src/lib/badge/badge.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#218 Update badge.component.scss
  projects/ion/src/lib/badge/badge.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#180 fix: [ion-177] selection adjustment
  projects/ion/src/lib/tab-group/tab-group.component.spec.ts
  projects/ion/src/lib/tab/tab.component.ts
Labels: hacktoberfest

#214 fix: icon sizes on buttons (#199)
  projects/ion/src/lib/button/button.component.html
  projects/ion/src/lib/button/button.component.scss
  projects/ion/src/lib/button/button.component.ts
  projects/ion/src/lib/core/types/button.ts
  stories/Button.stories.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#227 Fix header spacing
  projects/ion/src/lib/card/card.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#232 Change icon-color chip desable
  projects/ion/src/lib/chip/chip.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#230 Update chip.component.scss
  projects/ion/src/lib/chip/chip.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#213 fix: loading button colors (#197)
  projects/ion/src/lib/button/button.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#234 fix: correcting typography
  projects/ion/src/lib/card/card.component.scss
  projects/ion/src/styles/fonts/bold/SourceSansPro-Bold.eot
  projects/ion/src/styles/fonts/bold/SourceSansPro-Bold.ttf
  projects/ion/src/styles/fonts/bold/SourceSansPro-Bold.woff
  projects/ion/src/styles/fonts/bold/SourceSansPro-Bold.woff2
  projects/ion/src/styles/fonts/index.scss
  projects/ion/src/styles/fonts/regular/SourceSansPro-Regular.eot
  projects/ion/src/styles/fonts/regular/SourceSansPro-Regular.ttf
  projects/ion/src/styles/fonts/regular/SourceSansPro-Regular.woff
  projects/ion/src/styles/fonts/regular/SourceSansPro-Regular.woff2
  projects/ion/src/styles/fonts/semibold/SourceSansPro-Semibold.eot
  projects/ion/src/styles/fonts/semibold/SourceSansPro-Semibold.ttf
  projects/ion/src/styles/fonts/semibold/SourceSansPro-Semibold.woff
  projects/ion/src/styles/fonts/semibold/SourceSansPro-Semibold.woff2
Labels: hacktoberfest, important

#236 fix: disabled chip color adjustment (#195)
  projects/ion/src/lib/chip/chip.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#235 fix: notification height correction (#194)
  projects/ion/src/lib/notification/notification.component.html
  projects/ion/src/lib/notification/notification.component.scss
Labels: hacktoberfest, hacktoberfest-accepted

#161 146: notification animations
  projects/ion/src/lib/notification/notification.component.html
  projects/ion/src/lib/notification/notification.component.scss
  projects/ion/src/lib/notification/notification.component.spec.ts
  projects/ion/src/lib/notification/notification.component.ts
  projects/ion/src/lib/utils/animationsTypes.ts
  projects/ion/src/lib/utils/fadeAnimations.scss
  projects/ion/src/lib/utils/index.ts
  projects/ion/src/lib/utils/setTimer.ts
  stories/Notification.stories.ts
Labels: hacktoberfest

#223 162 create modal service
  .vscode/settings.json
  projects/ion/src/lib/button/button.component.scss
  projects/ion/src/lib/ion.module.ts
  projects/ion/src/lib/modal/component/modal.component.html
  projects/ion/src/lib/modal/component/modal.component.scss
  projects/ion/src/lib/modal/component/modal.component.spec.ts
  projects/ion/src/lib/modal/component/modal.component.ts
  projects/ion/src/lib/modal/mock/input.mock.component.ts
  projects/ion/src/lib/modal/mock/open-modal.mock.component.ts
  projects/ion/src/lib/modal/mock/select-mock.component.ts
  projects/ion/src/lib/modal/modal.service.spec.ts
  projects/ion/src/lib/modal/modal.service.ts
  projects/ion/src/lib/modal/models/modal.interface.ts
  projects/ion/src/public-api.ts
  stories/Modal.stories.mdx
  stories/Modal.stories.ts
Labels: enhancement, hacktoberfest, important

#244 feat: create new icon from condominium
  projects/ion/src/lib/icon/svgs/icons.ts
  projects/ion/src/lib/icon/svgs/iconsText/condominium.ts
  projects/ion/src/lib/icon/svgs/iconsText/index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#152 Input component
  projects/ion/src/lib/input/input.component.html
  projects/ion/src/lib/input/input.component.scss
  projects/ion/src/lib/input/input.component.spec.ts
  projects/ion/src/lib/input/input.component.ts
  stories/Input.stories.ts
Labels: hacktoberfest, hacktoberfest-accepted

#160 154 add dropdown in button
  projects/ion/src/lib/button/button.component.html
  projects/ion/src/lib/button/button.component.scss
  projects/ion/src/lib/button/button.component.spec.ts
  projects/ion/src/lib/button/button.component.ts
  projects/ion/src/lib/card/card.component.spec.ts
  projects/ion/src/lib/modal/component/modal.component.spec.ts
  projects/ion/src/lib/modal/modal.service.spec.ts
  projects/ion/src/lib/pagination/pagination.component.spec.ts
  projects/ion/src/lib/simple-menu/simple-menu.component.spec.ts
  stories/Button.stories.mdx
  stories/Card.stories.mdx
  stories/SimpleMenu.stories.ts
Labels: hacktoberfest

#166 Date-picker Component
  projects/ion/src/lib/date-picker/core/calendar.spec.ts
  projects/ion/src/lib/date-picker/core/calendar.ts
  projects/ion/src/lib/date-picker/core/day.spec.ts
  projects/ion/src/lib/date-picker/core/day.ts
  projects/ion/src/lib/date-picker/core/isLeapYear.spec.ts
  projects/ion/src/lib/date-picker/core/isLeapYear.ts
  projects/ion/src/lib/date-picker/core/month.spec.ts
  projects/ion/src/lib/date-picker/core/month.ts
  projects/ion/src/lib/date-picker/date-picker/date-picker.component.html
  projects/ion/src/lib/date-picker/date-picker/date-picker.component.scss
  projects/ion/src/lib/date-picker/date-picker/date-picker.component.spec.ts
  projects/ion/src/lib/date-picker/date-picker/date-picker.component.ts
  projects/ion/src/lib/ion.module.ts
  projects/ion/src/public-api.ts
  stories/Datepicker.stories.ts
Labels: hacktoberfest
