Repository Brisanet/ion, pull requests merged in 2023-07, with the labels that each got.

#730 fix: solved the problem where when setting all options with selected …
  projects/ion/src/lib/chip/chip.component.html
  projects/ion/src/lib/chip/chip.component.spec.ts
  projects/ion/src/lib/chip/chip.component.ts
  projects/ion/src/lib/dropdown/dropdown.component.spec.ts
  projects/ion/src/lib/dropdown/dropdown.component.ts
Labels: important

#736 383 notification service
  projects/ion/src/lib/core/types/notification.ts
  projects/ion/src/lib/icon/mock/list-icons.module.ts
  projects/ion/src/lib/notification/component/notification.component.html
  projects/ion/src/lib/notification/component/notification.component.scss
  projects/ion/src/lib/notification/component/notification.component.spec.ts
  projects/ion/src/lib/notification/component/notification.component.ts
  projects/ion/src/lib/notification/mock/open-notification-mock.component.ts
  projects/ion/src/lib/notification/notification.module.ts
  projects/ion/src/lib/notification/service/notification.container.component.ts
  projects/ion/src/lib/notification/service/notification.container.scss
  projects/ion/src/lib/notification/service/notification.service.spec.ts
  projects/ion/src/lib/notification/service/notification.service.ts
  projects/ion/src/public-api.ts
  stories/Notification.stories.ts
  yarn.lock
Labels: WIP

#773 fix: tooltip in action buttons adjustments
  projects/ion/src/lib/core/types/smart-table.ts
  projects/ion/src/lib/core/types/tooltip.ts
  projects/ion/src/lib/smart-table/smart-table.component.html
  projects/ion/src/lib/smart-table/smart-table.component.spec.ts
  projects/ion/src/lib/smart-table/smart-table.component.ts
  projects/ion/src/lib/table/utilsTable.ts
  stories/SmartTable.stories.ts
Labels: don't merge
